.\" Copyright (c) 2011 Marcelo Jorge Vieira <metal@debian.org>
'\"
'\" Redistribution and use in source and binary forms, with or without
'\" modification, are permitted provided that the following conditions
'\" are met:
'\"
'\"   * Redistributions of source code must retain the above
'\"     copyright notice, this list of conditions and the following
'\"     disclaimer.
'\"
'\"   * Redistributions in binary form must reproduce the above
'\"     copyright notice, this list of conditions and the following
'\"     disclaimer in the documentation and/or other materials
'\"     provided with the distribution.
'\"
'\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER “AS IS” AND ANY
'\" EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
'\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
'\" PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE
'\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
'\" OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
'\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
'\" PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
'\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
'\" TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
'\" THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
'\" SUCH DAMAGE.

.TH UGLIFYJS 1
.SH NAME
uglifyjs \- a JavaScript parser/compressor/beautifier

.SH SYNOPSIS
.B uglifyjs [options] [input_file]

.SH DESCRIPTION
This package implements a general-purpose JavaScript
parser/compressor/beautifier toolkit.

.SH OPTIONS

.TP
.B \-b, \-\-beautify
.br

.TP
.B \-i \fInumber-of-spaces\fR, \-\-indent \fInumber-of-spaces\fR
.br

.TP
.B \-q, \-\-quote\-keys
.br

.TP
.B \-mt, \-\-mangle\-toplevel
.br

.TP
.B \-nm, \-\-no\-mangle
.br

.TP
.B \-ns, \-\-no\-squeeze
.br

.TP
.B \-\-no\-seqs
.br

.TP
.B \-\-no\-dead\-code
.br

.TP
.B \-nc, \-\-no\-copyright
.br

.TP
.B \-o \fIfilename\fR, \-\-output \fIfilename\fR
.br

.TP
.B \-\-overwrite
.br

.TP
.B \-v, \-\-verbose
.br

.TP
.B \-\-ast
.br

.TP
.B \-\-unsafe
.br

.TP
.B \-\-max\-line\-len \fIvalue\fR
.br

.TP
.B \-\-reserved\-names \fIname1\fR, \fI$name2\fR, \fIname3\fR
.br

.TP
.B \-\-ascii
.br

.SH BUGS
The bug tracker can be reached by visiting the website
\fIhttps://github.com/mishoo/UglifyJS/issues\fR

Before sending a bug report, please verify that you have the latest
version of UglifyJS. Many bugs (major and minor) are fixed at each
release, and if yours is out of date, the problem may already have
been solved.

.SH ADDITIONAL INFORMATION

For further information, visit the website \fIhttps://github.com/mishoo/UglifyJS\fR
